# Generated by Django 5.1.2 on 2024-10-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateTimeField()),
                ('cidade_origem', models.CharField(max_length=100)),
                ('bairro_origem', models.CharField(max_length=100)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('bairro_destino', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('registro_academico', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('passageiro', 'Passageiro'), ('motorista', 'Motorista')], max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('pix', 'PIX')], max_length=10)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.agendamentoviagem')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='my_app.pessoa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='my_app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.agendamentoviagem')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_motorista', to='my_app.pessoa')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_passageiro', to='my_app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacoes', models.BooleanField(default=True)),
                ('modo_noturno', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.agendamentoviagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateTimeField()),
                ('cidade_origem', models.CharField(max_length=100)),
                ('bairro_origem', models.CharField(max_length=100)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('bairro_destino', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='agendamentoviagem',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pessoa'),
        ),
    ]
