# Generated by Django 5.1.1 on 2024-11-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                ("passageiros", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
