# Generated by Django 5.1.2 on 2024-11-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_carona'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentoviagem',
            name='horario_destino',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='agendamentoviagem',
            name='horario_origem',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
