# Generated by Django 5.1.2 on 2024-11-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_agendamentoviagem_horario_destino_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendamentoVisita',
        ),
    ]
