# Generated by Django 5.1.2 on 2024-11-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_delete_agendamentovisita'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='horario',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
