# Generated by Django 5.1.2 on 2024-11-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_carona_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentoviagem',
            old_name='horario_destino',
            new_name='hhorario_saida',
        ),
        migrations.RenameField(
            model_name='agendamentoviagem',
            old_name='horario_origem',
            new_name='horario_chegada',
        ),
    ]
