# Generated by Django 5.1.2 on 2024-11-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_horario_destino_agendamentoviagem_hhorario_saida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carona',
            old_name='horario',
            new_name='horario_chegada',
        ),
        migrations.AddField(
            model_name='carona',
            name='horario_saida',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
