# Generated by Django 5.1.2 on 2024-11-22 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_horario_carona_horario_chegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carona',
            name='horario_chegada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='carona',
            name='horario_saida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='carona',
            name='passageiros',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carona',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
